"""Read-only protocol the agents depend on. Keep it small; add methods only when an agent needs them."""
from __future__ import annotations

from typing import Protocol


class KnowledgeService(Protocol):
    def resolve_entity(self, mention: str) -> list[dict]: ...
    def entity_claims(self, entity_uid: str, context: dict | None = None) -> list[dict]: ...
    def entity_neighbors(self, entity_uid: str, rel_types: list[str] | None = None, hops: int = 1) -> list[dict]: ...
    def procedures_for(self, entity_uid: str | None = None, query: str | None = None) -> list[dict]: ...
    def procedure_steps(self, procedure_id: str) -> list[dict]: ...
    def search_chunks(self, query: str, k: int = 8, chunk_types: list[str] | None = None) -> list[dict]: ...
    def conflicts_for(self, entity_uid: str) -> list[dict]: ...
    def glossary(self, term: str) -> list[dict]: ...
    def document_profile(self, document_id: str) -> dict: ...
