class WorkbenchError(Exception): ...
class MissingEvidence(WorkbenchError): ...
class VerificationFailed(WorkbenchError): ...
class PolicyBlocked(WorkbenchError): ...
class ReplanRequested(WorkbenchError): ...
